stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker-compose build

test_job:
  stage: test
  script:
    - pytest

deploy_job:
  stage: deploy
  script:
    - docker-compose up -d
